---
rhel_baseline_packages:
  - podman
  - lvm2
  - xfsprogs
  - chrony
  - firewalld
  - policycoreutils-python-utils
  - openssl
  - jq
  - tar
  - gzip
  - logrotate
  - rsyslog
  - audit
  - curl

rhel_baseline_firewall_ports:
  - "{{ prisma_https_port }}/tcp"
  - "{{ prisma_comm_port }}/tcp"

rhel_baseline_firewall_services:
  - ssh

rhel_baseline_sysctl:
  vm.swappiness: "10"
  vm.max_map_count: "262144"
  fs.file-max: "2097152"
  net.core.somaxconn: "1024"
  net.ipv4.tcp_max_syn_backlog: "1024"

rhel_baseline_journald_max_use: "2G"
rhel_baseline_journald_keep_free: "1G"
