---
- name: Reload sshd
  ansible.builtin.systemd:
    name: sshd
    state: reloaded

- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload

- name: Reload sysctl
  ansible.builtin.command: sysctl --system

- name: Restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

- name: Restart chrony
  ansible.builtin.systemd:
    name: chronyd
    state: restarted
